package com.neegix.system.role.application.cqrs.query;
import com.neegix.application.query.IPageableQueryRepository;
import com.neegix.system.role.application.dto.RoleDTO;
import com.neegix.system.role.interfaces.vo.RoleVO;

 /**
  * This file is auto-generated by nebula-framework-generator.
  * The auto-generation plugin was developed using IntelliJ IDEA Community Edition.
  * Thanks to JetBrains for their outstanding contributions to the developer community.
  * <p>
  * The code generated by this tool is owned by the user of the tool.
  * The tool itself is copyrighted by <a href="https://www.neegix.com">https://www.neegix.com</a>.
  *
  * @author <a href="https://www.neegix.com">https://www.neegix.com</a>
  * @version 1.0.0
  * @since 2024-11-25 11:32:40
  */

public interface RoleQueryRepository extends IPageableQueryRepository<Long, RoleDTO, RoleVO> {

}
