package com.neegix.development.menu.infrastructure.repository.impl;

import com.neegix.application.query.NebulaSQL;
import com.neegix.development.menu.application.assembler.MenuAssembler;
import com.neegix.development.menu.application.repository.MenuQueryRepository;
import com.neegix.development.menu.infrastructure.repository.convert.MenuConverter;
import com.neegix.development.menu.infrastructure.repository.dataobject.MenuDO;
import com.neegix.development.menu.infrastructure.repository.mapper.MenuMapper;
import com.neegix.development.menu.interfaces.vo.MenuVO;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;

import java.util.List;

 /**
  * This file is auto-generated by nebula-framework-generator.
  * The auto-generation plugin was developed using IntelliJ IDEA Community Edition.
  * Thanks to JetBrains for their outstanding contributions to the developer community.
  * <p>
  * The code generated by this tool is owned by the user of the tool.
  * The tool itself is copyrighted by <a href="https://www.neegix.com">https://www.neegix.com</a>.
  *
  * @author <a href="https://www.neegix.com">https://www.neegix.com</a>
  * @version 1.0.0
  * @since 2024-11-21 16:19:51
  */

@Repository
public class MenuQueryRepositoryImpl implements MenuQueryRepository {

    @Autowired
    private MenuMapper menuMapper;

     @Override
     public List<MenuVO> findList(NebulaSQL nebulaSQL) {
        List<MenuDO> menuDOS = menuMapper.selectList(nebulaSQL);
        return MenuAssembler.INSTANCE.covertVO(MenuConverter.INSTANCE.covertDTOS(menuDOS));
     }
 }
