package com.neegix.log.operationLog.application.service.impl;

import com.neegix.application.command.BaseService;
import com.neegix.exception.BusinessRuntimeException;
import com.neegix.log.operationLog.application.cqrs.command.BatchDeleteOperationLogCommand;
import com.neegix.log.operationLog.application.cqrs.command.NewOperationLogCommand;
import com.neegix.log.operationLog.application.cqrs.command.UpdateOperationLogCommand;
import com.neegix.log.operationLog.application.cqrs.query.OperationLogQueryRepository;
import com.neegix.log.operationLog.application.service.OperationLogService;
import com.neegix.log.operationLog.domain.entity.OperationLogEntity;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.util.List;

 /**
  * This file is auto-generated by nebula-framework-generator.
  * The auto-generation plugin was developed using IntelliJ IDEA Community Edition.
  * Thanks to JetBrains for their outstanding contributions to the developer community.
  * <p>
  * The code generated by this tool is owned by the user of the tool.
  * The tool itself is copyrighted by <a href="https://www.neegix.com">https://www.neegix.com</a>.
  *
  * @author <a href="https://www.neegix.com">https://www.neegix.com</a>
  * @version 1.0.0
  * @since 2024-11-24 19:51:10
  */

@Service
public class OperationLogServiceImpl extends BaseService implements OperationLogService{
    @Autowired
    private OperationLogQueryRepository operationLogQueryRepository;

    @Override
    public Void createOperationLog(OperationLogEntity operationLogEntity) {
        return commandInvoker.execute(new NewOperationLogCommand(operationLogEntity));
    }

    @Override
    public Void modifyOperationLog(OperationLogEntity operationLogEntity) {
        return commandInvoker.execute(new UpdateOperationLogCommand(operationLogEntity));
    }

    @Override
    public Void removeOperationLog(List<Long> ids) {
        Integer count = operationLogQueryRepository.selectCount(ids);
        if (count.equals(0)){
            throw new BusinessRuntimeException("要删除的记录不存在！");
        }
        return commandInvoker.execute(new BatchDeleteOperationLogCommand(ids));
    }
}
