package com.neegix.system.role.application.service.impl;

import com.neegix.application.command.BaseService;
import com.neegix.exception.BusinessRuntimeException;
import com.neegix.system.role.application.cqrs.command.BatchDeleteRoleCommand;
import com.neegix.system.role.application.cqrs.command.NewRoleCommand;
import com.neegix.system.role.application.cqrs.command.UpdateRoleCommand;
import com.neegix.system.role.application.cqrs.query.RoleQueryRepository;
import com.neegix.system.role.application.service.RoleService;
import com.neegix.system.role.domain.entity.RoleEntity;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.util.List;

 /**
  * This file is auto-generated by nebula-framework-generator.
  * The auto-generation plugin was developed using IntelliJ IDEA Community Edition.
  * Thanks to JetBrains for their outstanding contributions to the developer community.
  * <p>
  * The code generated by this tool is owned by the user of the tool.
  * The tool itself is copyrighted by <a href="https://www.neegix.com">https://www.neegix.com</a>.
  *
  * @author <a href="https://www.neegix.com">https://www.neegix.com</a>
  * @version 1.0.0
  * @since 2024-11-25 11:32:40
  */

@Service
public class RoleServiceImpl extends BaseService implements RoleService{
    @Autowired
    private RoleQueryRepository roleQueryRepository;

    @Override
    public Void createRole(RoleEntity roleEntity) {
        return commandInvoker.execute(new NewRoleCommand(roleEntity));
    }

    @Override
    public Void modifyRole(RoleEntity roleEntity) {
        return commandInvoker.execute(new UpdateRoleCommand(roleEntity));
    }

    @Override
    public Void removeRole(List<Long> ids) {
        Integer count = roleQueryRepository.selectCount(ids);
        if (count.equals(0)){
            throw new BusinessRuntimeException("要删除的记录不存在！");
        }
        return commandInvoker.execute(new BatchDeleteRoleCommand(ids));
    }
}
