package com.neegix.log.exceptionLog.application.dto;
import java.time.Instant;
import lombok.Data;

 /**
  * This file is auto-generated by nebula-framework-generator.
  * The auto-generation plugin was developed using IntelliJ IDEA Community Edition.
  * Thanks to JetBrains for their outstanding contributions to the developer community.
  * <p>
  * The code generated by this tool is owned by the user of the tool.
  * The tool itself is copyrighted by <a href="https://www.neegix.com">https://www.neegix.com</a>.
  *
  * @author <a href="https://www.neegix.com">https://www.neegix.com</a>
  * @version 1.0.0
  * @since 2024-12-19 15:04:54
  */

@Data
public class ExceptionLogDTO {
    // ID
    private Long id;
    // 创建时间
    private Instant createTime;
    // 创建时间-开始
    private Instant startCreateTime;
    // 创建时间-结束
    private Instant endCreateTime;
    // 更新时间
    private Instant updateTime;
    // 更新时间-开始
    private Instant startUpdateTime;
    // 更新时间-结束
    private Instant endUpdateTime;
    // 创建人
    private Long createUser;
    // 更新人
    private Long updateUser;
    // 操作人
    private String user;
    // 模块
    private String module;
    // 类型
    private Integer type;
    // 描述
    private String description;
    // URI
    private String uri;
    // 全限定名
    private String fullName;
    // 异常信息
    private String exception;
}