package com.neegix.log.operationLog.interfaces.vo;

import com.neegix.inferfaces.vo.BaseVO;
import lombok.Data;

import java.time.LocalDate;

/**
  * This file is auto-generated by nebula-framework-generator.
  * The auto-generation plugin was developed using IntelliJ IDEA Community Edition.
  * Thanks to JetBrains for their outstanding contributions to the developer community.
  * <p>
  * The code generated by this tool is owned by the user of the tool.
  * The tool itself is copyrighted by <a href="https://www.neegix.com">https://www.neegix.com</a>.
  *
  * @author <a href="https://www.neegix.com">https://www.neegix.com</a>
  * @version 1.0.0
  * @since 2024-11-24 19:51:10
  */

@Data
public class OperationLogVO implements BaseVO {
    private String user;
    // 创建时间
    private LocalDate createTime;
    // 创建人
    private Long createUser;
    // 描述
    private String description;
    // ID
    private Long id;
    // 模块
    private String module;
    // 类型
    private Integer type;
    // 更新时间
    private LocalDate updateTime;
    // 更新人
    private Long updateUser;
}


