package com.neegix.organization.psn.application.dto;

import lombok.Data;

/**
 * This file is auto-generated by nebula-framework-generator.
 * The auto-generation plugin was developed using IntelliJ IDEA Community Edition.
 * Thanks to JetBrains for their outstanding contributions to the developer community.
 * <p>
 * The code generated by this tool is owned by the user of the tool.
 * The tool itself is copyrighted by <a href="https://www.neegix.com">https://www.neegix.com</a>.
 *
 * @author <a href="https://www.neegix.com">https://www.neegix.com</a>
 * @version 1.0.0
 * @since 2024-12-11 15:13:32
 */

@Data
public class PsnWorkInfoDTO {
   private Long pkPsn;
   private Long pkBizUnit;
   private Long pkDept;
   private Long pkPost;
   private String code;
   private String type;
   private Boolean major;
   private String start;
   private String end;
   private String position;
}