
package com.neegix.log.loginLog.domain.entity;

import com.neegix.base.BaseEntity;
import lombok.Data;
import lombok.EqualsAndHashCode;

 /**
  * This file is auto-generated by nebula-framework-generator.
  * The auto-generation plugin was developed using IntelliJ IDEA Community Edition.
  * Thanks to JetBrains for their outstanding contributions to the developer community.
  * <p>
  * The code generated by this tool is owned by the user of the tool.
  * The tool itself is copyrighted by <a href="https://www.neegix.com">https://www.neegix.com</a>.
  *
  * @author <a href="https://www.neegix.com">https://www.neegix.com</a>
  * @version 1.0.0
  * @since 2024-12-19 15:39:21
  */

@EqualsAndHashCode(callSuper = true)
@Data
public class LoginLogEntity extends BaseEntity {
     // 登录人
     private String user;
    // IP
    private String ip;
    // 地区
    private String area;
    // 类型（1 浏览器 2 移动端 3 TV端）
    private Integer type;
    // 客户端
    private String client;
    // 是否启用（0 否 1 是）
    private Boolean enabled;
    // 是否删除（0 否 1 是）
    private Boolean deleted;
}