package com.neegix.organization.bizUnit.infrastructure.repository.mapper;

import com.neegix.base.BaseMapper;
import com.neegix.organization.bizUnit.infrastructure.repository.dataobject.BizUnitDO;
import org.apache.ibatis.annotations.Mapper;

 /**
  * This file is auto-generated by nebula-framework-generator.
  * The auto-generation plugin was developed using IntelliJ IDEA Community Edition.
  * Thanks to JetBrains for their outstanding contributions to the developer community.
  * <p>
  * The code generated by this tool is owned by the user of the tool.
  * The tool itself is copyrighted by <a href="https://www.neegix.com">https://www.neegix.com</a>.
  *
  * @author <a href="https://www.neegix.com">https://www.neegix.com</a>
  * @version 1.0.0
  * @since 2024-12-10 10:58:59
  */

@Mapper
public interface BizUnitMapper extends BaseMapper<BizUnitDO, Long> {
}