package com.neegix.development.api.application.repository;

import com.neegix.application.query.IQueryRepository;
import com.neegix.application.query.NebulaSQL;
import com.neegix.base.PageVO;
import com.neegix.development.api.interfaces.vo.ApiListVO;
import com.neegix.development.api.interfaces.vo.ApiVO;

/**
  * This file is auto-generated by nebula-framework-generator.
  * The auto-generation plugin was developed using IntelliJ IDEA Community Edition.
  * Thanks to JetBrains for their outstanding contributions to the developer community.
  * <p>
  * The code generated by this tool is owned by the user of the tool.
  * The tool itself is copyrighted by <a href="https://www.neegix.com">https://www.neegix.com</a>.
  *
  * @author <a href="https://www.neegix.com">https://www.neegix.com</a>
  * @version 1.0.0
  * @since 2024-11-22 11:43:14
  */

public interface ApiQueryRepository extends IQueryRepository<Long, NebulaSQL, ApiVO> {
    PageVO<ApiListVO> findPage(Integer currentPage, Integer pageSize, NebulaSQL nebulaSQL);
}
