<#assign currentTime = .now>
    <#assign extraColumns = ["create_time", "create_user", "update_time", "update_user"]>

package ${templateTable.packageName}.${templateTable.javaTableName[0]?lower_case+templateTable.javaTableName[1..]}.interfaces.form;

import lombok.Data;
<#if templateTable.columns?exists>
    <#list templateTable.columns as column>
        <#if !(column.fullyQualifiedJavaType?contains("lang")) && column.isFirstImportPackage() && !extraColumns?seq_contains(column.sqlName)>
import ${column.fullyQualifiedJavaType};
        </#if>
        <#if column.isFirstEmptyPackage()>
import jakarta.validation.constraints.NotEmpty;
        </#if>
    </#list>
</#if>

 /**
  * This file is auto-generated by nebula-framework-generator.
  * The auto-generation plugin was developed using IntelliJ IDEA Community Edition.
  * Thanks to JetBrains for their outstanding contributions to the developer community.
  * <p>
  * The code generated by this tool is owned by the user of the tool.
  * The tool itself is copyrighted by <a href="${templateTable.copyright}">${templateTable.copyright}</a>.
  *
  * @author <a href="${templateTable.copyright}">${templateTable.copyright}</a>
  * @version ${templateTable.version}
  * @since ${currentTime?string("yyyy-MM-dd HH:mm:ss")}
  */

@Data
public class Update${templateTable.javaTableName}Form {
    <#if templateTable.columns?exists>
        <#list templateTable.columns as column>
            <#if !extraColumns?seq_contains(column.sqlName)>
    // ${column.description}
                <#if column.isAllowedNull()>
    @NotEmpty(message="${column.description}不能为空")
                </#if>
    private ${column.javaType} ${column.javaName};
            </#if>
        </#list>
    </#if>
}


