
package com.neegix.log.exceptionLog.domain.entity;

import com.neegix.base.BaseEntity;
import lombok.Data;
import lombok.EqualsAndHashCode;

 /**
  * This file is auto-generated by nebula-framework-generator.
  * The auto-generation plugin was developed using IntelliJ IDEA Community Edition.
  * Thanks to JetBrains for their outstanding contributions to the developer community.
  * <p>
  * The code generated by this tool is owned by the user of the tool.
  * The tool itself is copyrighted by <a href="https://www.neegix.com">https://www.neegix.com</a>.
  *
  * @author <a href="https://www.neegix.com">https://www.neegix.com</a>
  * @version 1.0.0
  * @since 2024-12-19 15:04:54
  */

@EqualsAndHashCode(callSuper = true)
@Data
public class ExceptionLogEntity extends BaseEntity {
    // 操作人
    private String user;
    // 模块
    private String module;
    // 类型
    private Integer type;
    // 描述
    private String description;
    // URI
    private String uri;
    // 全限定名
    private String fullName;
    // 异常信息
    private String exception;
}