<#assign currentTime = .now>
package ${templateTable.packageName}.infrastructure.repository.dataobject;

<#if templateTable.columns?exists>
    <#list templateTable.columns as column>
        <#if !(column.fullyQualifiedJavaType?contains("lang"))>
import ${column.fullyQualifiedJavaType};
        </#if>
    </#list>
</#if>
import com.neegix.base.BaseDO;
import lombok.Data;
import lombok.EqualsAndHashCode;

 /**
  * This file is auto-generated by nebula-framework-generator.
  * The auto-generation plugin was developed using IntelliJ IDEA Community Edition.
  * Thanks to JetBrains for their outstanding contributions to the developer community.
  *
  * The code generated by this tool is owned by the user of the tool.
  * The tool itself is copyrighted by ${templateTable.copyright}.
  *
  * @author ${templateTable.copyright}
  * @version ${templateTable.version}
  * @since ${currentTime?string("yyyy-MM-dd HH:mm:ss")}
  */
@EqualsAndHashCode(callSuper = true)
@Data
public class ${templateTable.javaTableName}DO extends BaseDO {
    <#if templateTable.columns?exists>
        <#list templateTable.columns as column>
    // ${column.description}
    private ${column.javaType} ${column.javaName};
        </#list>
    </#if>
}