
package com.neegix.system.user.application.repository;

import com.neegix.application.query.IPageableQueryRepository;
import com.neegix.application.query.NebulaSQL;
import com.neegix.system.user.interfaces.vo.UserForExportVO;
import com.neegix.system.user.interfaces.vo.UserForListVO;

import java.util.List;

/**
  * This file is auto-generated by nebula-framework-generator.
  * The auto-generation plugin was developed using IntelliJ IDEA Community Edition.
  * Thanks to JetBrains for their outstanding contributions to the developer community.
  * <p>
  * The code generated by this tool is owned by the user of the tool.
  * The tool itself is copyrighted by <a href="https://www.neegix.com">https://www.neegix.com</a>.
  *
  * @author <a href="https://www.neegix.com">https://www.neegix.com</a>
  * @version 1.0.0
  * @since 2024-12-03 11:47:28
  */

public interface UserQueryRepository extends IPageableQueryRepository<Long, NebulaSQL, UserForListVO> {
    List<UserForExportVO> findUsers();
}
