
package com.neegix.organization.psn.application.cqrs.query;

import com.neegix.application.query.IQueryRepository;
import com.neegix.application.query.NebulaSQL;
import com.neegix.base.PageVO;
import com.neegix.organization.psn.interfaces.vo.PsnVO;

import java.util.List;

/**
  * This file is auto-generated by nebula-framework-generator.
  * The auto-generation plugin was developed using IntelliJ IDEA Community Edition.
  * Thanks to JetBrains for their outstanding contributions to the developer community.
  * <p>
  * The code generated by this tool is owned by the user of the tool.
  * The tool itself is copyrighted by <a href="https://www.neegix.com">https://www.neegix.com</a>.
  *
  * @author <a href="https://www.neegix.com">https://www.neegix.com</a>
  * @version 1.0.0
  * @since 2024-12-11 15:13:32
  */

public interface PsnQueryRepository extends IQueryRepository<Long, NebulaSQL, PsnVO> {
  PageVO<PsnVO> findPage(Integer currentPage, Integer pageSize, NebulaSQL nebulaSQL);
  List<Long> findPsnPkByBizUnitAndDept(Long pkBizUnit, Long pkDept);
}
