package com.neegix.log.operationLog.infrastructure.repository.impl;

import com.neegix.application.query.NebulaSQL;
import com.neegix.base.PageVO;
import com.neegix.log.operationLog.application.assembler.OperationLogAssembler;
import com.neegix.log.operationLog.application.repository.OperationLogQueryRepository;
import com.neegix.log.operationLog.infrastructure.repository.dataobject.OperationLogDO;
import com.neegix.log.operationLog.infrastructure.repository.mapper.OperationLogMapper;
import com.neegix.log.operationLog.interfaces.vo.OperationLogVO;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;

import java.util.List;

 /**
  * This file is auto-generated by nebula-framework-generator.
  * The auto-generation plugin was developed using IntelliJ IDEA Community Edition.
  * Thanks to JetBrains for their outstanding contributions to the developer community.
  * <p>
  * The code generated by this tool is owned by the user of the tool.
  * The tool itself is copyrighted by <a href="https://www.neegix.com">https://www.neegix.com</a>.
  *
  * @author <a href="https://www.neegix.com">https://www.neegix.com</a>
  * @version 1.0.0
  * @since 2024-11-24 19:51:10
  */

@Repository
public class OperationLogQueryRepositoryImpl implements OperationLogQueryRepository {

    @Autowired
    private OperationLogMapper operationLogMapper;

    @Override
    public PageVO<OperationLogVO> findPage(Integer currentPage, Integer pageSize, NebulaSQL nebulaSQL) {
        nebulaSQL.setPager(currentPage, pageSize);
        List<OperationLogDO> result = operationLogMapper.selectList(nebulaSQL);
        Long total = operationLogMapper.selectCount(nebulaSQL);
        PageVO<OperationLogVO> page = new PageVO<>(currentPage, pageSize);
        page.setTotal(total);
        page.setResult(OperationLogAssembler.INSTANCE.covertVO(result));
        return page;
    }
}
