package com.neegix.system.role.interfaces.vo;

import com.neegix.inferfaces.vo.BaseVO;
import lombok.Data;

import java.time.LocalDate;
import java.util.List;

/**
  * This file is auto-generated by nebula-framework-generator.
  * The auto-generation plugin was developed using IntelliJ IDEA Community Edition.
  * Thanks to JetBrains for their outstanding contributions to the developer community.
  * <p>
  * The code generated by this tool is owned by the user of the tool.
  * The tool itself is copyrighted by <a href="https://www.neegix.com">https://www.neegix.com</a>.
  *
  * @author <a href="https://www.neegix.com">https://www.neegix.com</a>
  * @version 1.0.0
  * @since 2024-11-25 11:32:40
  */

@Data
public class RoleVO implements BaseVO {
    // 创建时间
    private LocalDate createTime;
    // 创建人
    private Long createUser;
    // 是否删除（0 否 1 是）
    private Boolean deleted;
    // 是否启用（0 否 1 是）
    private Boolean enabled;
    // ID
    private Long id;
    // 角色名称
    private String name;
    // 密码
    private String description;
    // 更新时间
    private LocalDate updateTime;
    // 更新人
    private Long updateUser;

    private List<ApiPermissionVO> apiPermissions;

    private List<PagePermissionVO> pagePermissions;
}


