package com.neegix.development.api.application.service.command.mapper;

import com.neegix.development.api.application.service.command.CreateApiCommand;
import com.neegix.development.api.application.service.command.UpdateApiCommand;
import com.neegix.development.api.interfaces.form.CreateApiForm;
import com.neegix.development.api.interfaces.form.UpdateApiForm;
import org.mapstruct.Mapper;
import org.mapstruct.factory.Mappers;

/**
 * This file is auto-generated by nebula-framework-generator.
 * The auto-generation plugin was developed using IntelliJ IDEA Community Edition.
 * Thanks to JetBrains for their outstanding contributions to the developer community.
 * <p>
 * The code generated by this tool is owned by the user of the tool.
 * The tool itself is copyrighted by <a href="https://www.neegix.com">https://www.neegix.com</a>.
 *
 * @author <a href="https://www.neegix.com">https://www.neegix.com</a>
 * @version 1.0.0
 * @since 2024-11-22 11:43:14
 */

@Mapper
public interface ApiCommandMapper {
   ApiCommandMapper INSTANCE = Mappers.getMapper(ApiCommandMapper.class);

   CreateApiCommand covertToCreateApiCommand(CreateApiForm createApiForm);

   UpdateApiCommand covertToUpdateApiCommand(UpdateApiForm updateApiForm);

}