package com.neegix.development.menu.interfaces.controller;

import com.neegix.base.PageVO;
import com.neegix.development.api.application.assembler.ApiAssembler;
import com.neegix.development.api.domain.entity.ApiEntity;
import com.neegix.development.menu.domain.entity.MenuEntity;
import com.neegix.exception.BusinessRuntimeException;
import com.neegix.result.Result;
import com.neegix.development.menu.application.assembler.MenuAssembler;
import com.neegix.development.menu.application.cqrs.query.MenuQueryRepository;
import com.neegix.development.menu.interfaces.vo.MenuVO;
import com.neegix.development.menu.application.service.MenuService;
import com.neegix.development.menu.interfaces.form.NewMenuForm;
import com.neegix.development.menu.interfaces.form.QueryMenuForm;
import com.neegix.development.menu.interfaces.form.UpdateMenuForm;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import java.util.List;
import java.util.Optional;

 /**
  * This file is auto-generated by nebula-framework-generator.
  * The auto-generation plugin was developed using IntelliJ IDEA Community Edition.
  * Thanks to JetBrains for their outstanding contributions to the developer community.
  * <p>
  * The code generated by this tool is owned by the user of the tool.
  * The tool itself is copyrighted by <a href="https://www.neegix.com">https://www.neegix.com</a>.
  *
  * @author <a href="https://www.neegix.com">https://www.neegix.com</a>
  * @version 1.0.0
  * @since 2024-11-21 16:19:51
  */

@RestController
@RequestMapping("/api/v1/menu")
public class MenuController {

    @Autowired
    private MenuQueryRepository menuQueryRepository;

    @Autowired
    private MenuService menuService;

    @PreAuthorize("hasAuthority('development:menu:add')")
    @PostMapping
    public Result<Void> createMenu(@RequestBody NewMenuForm menuForm){
        Void result = menuService.createMenu(MenuAssembler.INSTANCE.covertEntity(menuForm));
        return Result.success("创建成功", result);
    }

    @PreAuthorize("hasAuthority('development:menu:modify')")
    @PutMapping("/{id}")
    public Result<Void> updateMenu(@PathVariable Long id, @RequestBody UpdateMenuForm menuForm){
        MenuEntity menuEntity = MenuAssembler.INSTANCE.covertEntity(menuForm);
        menuEntity.setId(id);
        Void result = menuService.modifyMenu(menuEntity);
        return Result.success("更新成功",result);
    }

    @PreAuthorize("hasAuthority('development:menu:list')")
    @GetMapping
    public Result<List<MenuVO>> getMenus(@RequestBody(required = false) QueryMenuForm menuForm){
        if(menuForm == null) {
            menuForm = new QueryMenuForm();
        }
        List<MenuVO> data = menuQueryRepository.findList(MenuAssembler.INSTANCE.covertDTO(menuForm));
        return Result.success("查询成功",data);
    }

    @PreAuthorize("hasAuthority('development:menu:get')")
    @GetMapping("/{id}")
    public Result<MenuVO> getMenuById(@PathVariable("id") Long id) {
        Optional<MenuVO> optional = menuQueryRepository.findById(id);
        return Result.success("获取成功", optional.orElseThrow(()-> new BusinessRuntimeException("查询结果不存在")));
    }


    @PreAuthorize("hasAuthority('development:menu:remove')")
    @DeleteMapping
    public Result<Void> removeMenu(@RequestBody List<Long> ids){
        return Result.success("删除成功", menuService.removeMenu(ids));
    }
}