package com.neegix.system.user.application.cqrs.command;

import com.neegix.application.command.ICommand;
import com.neegix.system.user.domain.entity.UserEntity;
import com.neegix.system.user.infrastructure.repository.convert.UserConverter;
import com.neegix.system.user.infrastructure.repository.mapper.UserMapper;
import org.springframework.context.ApplicationContext;

 /**
  * This file is auto-generated by nebula-framework-generator.
  * The auto-generation plugin was developed using IntelliJ IDEA Community Edition.
  * Thanks to JetBrains for their outstanding contributions to the developer community.
  * <p>
  * The code generated by this tool is owned by the user of the tool.
  * The tool itself is copyrighted by <a href="https://www.neegix.com">https://www.neegix.com</a>.
  *
  * @author <a href="https://www.neegix.com">https://www.neegix.com</a>
  * @version 1.0.0
  * @since 2024-12-03 11:47:28
  */

public class UpdateUserCommand implements ICommand<Void> {
    private final UserEntity userEntity;

    public UpdateUserCommand(UserEntity userEntity) {
        this.userEntity = userEntity;
    }

    @Override
    public Void execute(ApplicationContext context) {
        UserMapper userMapper = context.getBean(UserMapper.class);
        userMapper.updateByPrimaryKey(UserConverter.INSTANCE.covertDO(userEntity));
        return null;
    }
}
