package com.neegix.organization.bizUnit.application.service.impl;

import com.neegix.application.command.BaseService;
import com.neegix.exception.BusinessRuntimeException;
import com.neegix.organization.bizUnit.application.cqrs.command.BatchDeleteBizUnitCommand;
import com.neegix.organization.bizUnit.application.cqrs.command.NewBizUnitCommand;
import com.neegix.organization.bizUnit.application.cqrs.command.UpdateBizUnitCommand;
import com.neegix.organization.bizUnit.application.cqrs.query.BizUnitQueryRepository;
import com.neegix.organization.bizUnit.application.service.BizUnitService;
import com.neegix.organization.bizUnit.domain.entity.BizUnitEntity;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.util.List;

 /**
  * This file is auto-generated by nebula-framework-generator.
  * The auto-generation plugin was developed using IntelliJ IDEA Community Edition.
  * Thanks to JetBrains for their outstanding contributions to the developer community.
  * <p>
  * The code generated by this tool is owned by the user of the tool.
  * The tool itself is copyrighted by <a href="https://www.neegix.com">https://www.neegix.com</a>.
  *
  * @author <a href="https://www.neegix.com">https://www.neegix.com</a>
  * @version 1.0.0
  * @since 2024-12-10 10:58:59
  */

@Service
public class BizUnitServiceImpl extends BaseService implements BizUnitService{
    @Autowired
    private BizUnitQueryRepository bizUnitQueryRepository;

    @Override
    public Void createBizUnit(BizUnitEntity bizUnitEntity) {
        return commandInvoker.execute(new NewBizUnitCommand(bizUnitEntity));
    }

    @Override
    public Void modifyBizUnit(BizUnitEntity bizUnitEntity) {
        return commandInvoker.execute(new UpdateBizUnitCommand(bizUnitEntity));
    }

    @Override
    public Void removeBizUnit(List<Long> ids) {
        Integer count = bizUnitQueryRepository.selectCount(ids);
        if (count.equals(0)){
            throw new BusinessRuntimeException("要删除的记录不存在！");
        }
        return commandInvoker.execute(new BatchDeleteBizUnitCommand(ids));
    }
}
