package com.neegix.development.menu.interfaces.vo;

import com.neegix.base.BaseVO;
import lombok.Data;
import java.time.Instant;

 /**
  * This file is auto-generated by nebula-framework-generator.
  * The auto-generation plugin was developed using IntelliJ IDEA Community Edition.
  * Thanks to JetBrains for their outstanding contributions to the developer community.
  * <p>
  * The code generated by this tool is owned by the user of the tool.
  * The tool itself is copyrighted by <a href="https://www.neegix.com">https://www.neegix.com</a>.
  *
  * @author <a href="https://www.neegix.com">https://www.neegix.com</a>
  * @version 1.0.0
  * @since 2024-11-21 16:19:51
  */

@Data
public class MenuVO implements BaseVO {
    // ID
    private Long id;
    // 创建时间
    private Instant createTime;
    // 更新时间
    private Instant updateTime;
    // 创建人
    private Long createUser;
    // 更新人
    private Long updateUser;
    // 父ID
    private Long pid;
    // 名称
    private String name;
    // 权限标识
    private String access;
    // 类型
    private Integer type;
    // 顺序
    private Integer order;
    // 是否启用（0 否 1 是）
    private Boolean enabled;
    // 是否删除（0 否 1 是）
    private Boolean deleted;
}


