package com.neegix.log.loginLog.application.assembler;

import com.neegix.log.loginLog.domain.entity.LoginLogEntity;
import com.neegix.log.loginLog.infrastructure.repository.dataobject.LoginLogDO;
import com.neegix.log.loginLog.interfaces.vo.LoginLogVO;
import org.mapstruct.Mapper;
import org.mapstruct.factory.Mappers;

import java.util.List;

 /**
  * This file is auto-generated by nebula-framework-generator.
  * The auto-generation plugin was developed using IntelliJ IDEA Community Edition.
  * Thanks to JetBrains for their outstanding contributions to the developer community.
  * <p>
  * The code generated by this tool is owned by the user of the tool.
  * The tool itself is copyrighted by <a href="https://www.neegix.com">https://www.neegix.com</a>.
  *
  * @author <a href="https://www.neegix.com">https://www.neegix.com</a>
  * @version 1.0.0
  * @since 2024-12-19 15:39:21
  */

@Mapper
public interface LoginLogAssembler {
    LoginLogAssembler INSTANCE = Mappers.getMapper(LoginLogAssembler.class);

    List<LoginLogVO> covertVO(List<LoginLogDO> LoginLogDOs);

    LoginLogVO covertVO(LoginLogEntity entity);
}