package com.neegix.log.loginLog.application.assembler;

import com.neegix.log.loginLog.application.dto.LoginLogDTO;
import com.neegix.log.loginLog.interfaces.vo.LoginLogVO;
import com.neegix.log.loginLog.domain.entity.LoginLogEntity;
import com.neegix.log.loginLog.interfaces.form.NewLoginLogForm;
import com.neegix.log.loginLog.interfaces.form.QueryLoginLogForm;
import com.neegix.log.loginLog.interfaces.form.UpdateLoginLogForm;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.factory.Mappers;
import java.util.List;

 /**
  * This file is auto-generated by nebula-framework-generator.
  * The auto-generation plugin was developed using IntelliJ IDEA Community Edition.
  * Thanks to JetBrains for their outstanding contributions to the developer community.
  * <p>
  * The code generated by this tool is owned by the user of the tool.
  * The tool itself is copyrighted by <a href="https://www.neegix.com">https://www.neegix.com</a>.
  *
  * @author <a href="https://www.neegix.com">https://www.neegix.com</a>
  * @version 1.0.0
  * @since 2024-12-19 15:39:21
  */

@Mapper
public interface LoginLogAssembler {
    LoginLogAssembler INSTANCE = Mappers.getMapper(LoginLogAssembler.class);


    @Mapping(target = "id", ignore = true)
    @Mapping(target = "createTime", ignore = true)
    @Mapping(target = "updateTime", ignore = true)
    @Mapping(target = "createUser", ignore = true)
    @Mapping(target = "updateUser", ignore = true)
    LoginLogEntity covertEntity(NewLoginLogForm newLoginLogForm);

    @Mapping(target = "createTime", ignore = true)
    @Mapping(target = "updateTime", ignore = true)
    @Mapping(target = "createUser", ignore = true)
    @Mapping(target = "updateUser", ignore = true)
    LoginLogEntity covertEntity(UpdateLoginLogForm updateLoginLogForm);

    @Mapping(target = "createTime", ignore = true)
    @Mapping(target = "updateTime", ignore = true)
    LoginLogDTO covertDTO(QueryLoginLogForm queryLoginLogForm);

    List<LoginLogVO> covertVO(List<LoginLogDTO> LoginLogDTOs);

    LoginLogVO covertVO(LoginLogDTO queryLoginLogDTO);
}