<#assign currentTime = .now>
<#-- 包名 -->
<#assign packageName = templateTable.packageName>

<#-- 模块名 -->
<#assign moduleName = templateTable.javaTableName[0]?lower_case+templateTable.javaTableName[1..]>

<#-- 类名 -->
<#assign className = templateTable.javaTableName>

package ${packageName}.${moduleName}.application.cqrs.query;
import com.neegix.application.query.IPageableQueryRepository;
import ${packageName}.${moduleName}.application.dto.${className}DTO;
import ${packageName}.${moduleName}.interfaces.vo.${className}VO;

 /**
  * This file is auto-generated by nebula-framework-generator.
  * The auto-generation plugin was developed using IntelliJ IDEA Community Edition.
  * Thanks to JetBrains for their outstanding contributions to the developer community.
  * <p>
  * The code generated by this tool is owned by the user of the tool.
  * The tool itself is copyrighted by <a href="${templateTable.copyright}">${templateTable.copyright}</a>.
  *
  * @author <a href="${templateTable.copyright}">${templateTable.copyright}</a>
  * @version ${templateTable.version}
  * @since ${currentTime?string("yyyy-MM-dd HH:mm:ss")}
  */

public interface ${className}QueryRepository extends IPageableQueryRepository<<#if templateTable.columns?exists><#list templateTable.columns as column><#if column.isPrimaryKey()>${column.javaType}</#if></#list></#if>, ${className}DTO, ${className}VO> {

}
