
package com.neegix.development.menu.interfaces.form;

import lombok.Data;
import jakarta.validation.constraints.NotEmpty;

 /**
  * This file is auto-generated by nebula-framework-generator.
  * The auto-generation plugin was developed using IntelliJ IDEA Community Edition.
  * Thanks to JetBrains for their outstanding contributions to the developer community.
  * <p>
  * The code generated by this tool is owned by the user of the tool.
  * The tool itself is copyrighted by <a href="https://www.neegix.com">https://www.neegix.com</a>.
  *
  * @author <a href="https://www.neegix.com">https://www.neegix.com</a>
  * @version 1.0.0
  * @since 2024-11-21 16:19:51
  */

@Data
public class UpdateMenuForm {
    // ID
    @NotEmpty(message="ID不能为空")
    private Long id;
    // 父ID
    @NotEmpty(message="父ID不能为空")
    private Long pid;
    // 名称
    @NotEmpty(message="名称不能为空")
    private String name;
    // 权限标识
    private String access;
    // 类型
    private Integer type;
    // 是否启用（0 否 1 是）
    private Boolean enabled;
    // 是否删除（0 否 1 是）
    private Boolean deleted;
}


