package com.neegix.development.api.application.cqrs.command;

import com.neegix.application.command.ICommand;
import com.neegix.development.api.domain.entity.ApiEntity;
import com.neegix.development.api.infrastructure.repository.convert.ApiConverter;
import com.neegix.development.api.infrastructure.repository.mapper.ApiMapper;
import org.springframework.context.ApplicationContext;

 /**
  * This file is auto-generated by nebula-framework-generator.
  * The auto-generation plugin was developed using IntelliJ IDEA Community Edition.
  * Thanks to JetBrains for their outstanding contributions to the developer community.
  * <p>
  * The code generated by this tool is owned by the user of the tool.
  * The tool itself is copyrighted by <a href="https://www.neegix.com">https://www.neegix.com</a>.
  *
  * @author <a href="https://www.neegix.com">https://www.neegix.com</a>
  * @version 1.0.0
  * @since 2024-11-22 11:43:14
  */

public class UpdateApiCommand implements ICommand<Void> {
    private final ApiEntity apiEntity;

    public UpdateApiCommand(ApiEntity apiEntity) {
        this.apiEntity = apiEntity;
    }

    @Override
    public Void execute(ApplicationContext context) {
        ApiMapper apiMapper = context.getBean(ApiMapper.class);
        apiMapper.updateByPrimaryKey(ApiConverter.INSTANCE.covertDO(apiEntity));
        return null;
    }
}
