package com.neegix.organization.psn.application.assembler;

import com.neegix.organization.psn.application.service.command.CreatePsnCommand;
import com.neegix.organization.psn.application.service.command.UpdatePsnCommand;
import com.neegix.organization.psn.domain.entity.PsnEntity;
import com.neegix.organization.psn.infrastructure.repository.dataobject.PsnDO;
import com.neegix.organization.psn.interfaces.vo.PsnVO;
import org.mapstruct.Mapper;
import org.mapstruct.factory.Mappers;

import java.util.List;

 /**
  * This file is auto-generated by nebula-framework-generator.
  * The auto-generation plugin was developed using IntelliJ IDEA Community Edition.
  * Thanks to JetBrains for their outstanding contributions to the developer community.
  * <p>
  * The code generated by this tool is owned by the user of the tool.
  * The tool itself is copyrighted by <a href="https://www.neegix.com">https://www.neegix.com</a>.
  *
  * @author <a href="https://www.neegix.com">https://www.neegix.com</a>
  * @version 1.0.0
  * @since 2024-12-11 15:13:32
  */

@Mapper
public interface PsnAssembler {
    PsnAssembler INSTANCE = Mappers.getMapper(PsnAssembler.class);
    PsnEntity covertEntity(CreatePsnCommand psnCommand);

    PsnEntity covertEntity(UpdatePsnCommand psnCommand);

    List<PsnVO> covertVO(List<PsnDO> PsnDOs);

    PsnVO covertVO(PsnEntity psnEntity);
}