
package com.neegix.system.role.domain.entity;

import com.neegix.base.BaseEntity;
import lombok.Data;
import lombok.EqualsAndHashCode;

import java.util.List;

/**
  * This file is auto-generated by nebula-framework-generator.
  * The auto-generation plugin was developed using IntelliJ IDEA Community Edition.
  * Thanks to JetBrains for their outstanding contributions to the developer community.
  * <p>
  * The code generated by this tool is owned by the user of the tool.
  * The tool itself is copyrighted by <a href="https://www.neegix.com">https://www.neegix.com</a>.
  *
  * @author <a href="https://www.neegix.com">https://www.neegix.com</a>
  * @version 1.0.0
  * @since 2024-11-25 11:32:40
  */

@EqualsAndHashCode(callSuper = true)
@Data
public class RoleEntity extends BaseEntity {
    // 是否删除（0 否 1 是）
    private Boolean deleted;
    // 是否启用（0 否 1 是）
    private Boolean enabled;
    // 角色名称
    private String name;
    // 描述
    private String description;
    // 接口权限
    private List<Long> apiPermissions;
    // 菜单和功能权限
    private List<RoleMenuEntity> pagePermissions;
}