package com.neegix.log.exceptionLog.application.assembler;

import com.neegix.log.exceptionLog.domain.entity.ExceptionLogEntity;
import com.neegix.log.exceptionLog.interfaces.vo.ExceptionLogVO;
import org.mapstruct.Mapper;
import org.mapstruct.factory.Mappers;

 /**
  * This file is auto-generated by nebula-framework-generator.
  * The auto-generation plugin was developed using IntelliJ IDEA Community Edition.
  * Thanks to JetBrains for their outstanding contributions to the developer community.
  * <p>
  * The code generated by this tool is owned by the user of the tool.
  * The tool itself is copyrighted by <a href="https://www.neegix.com">https://www.neegix.com</a>.
  *
  * @author <a href="https://www.neegix.com">https://www.neegix.com</a>
  * @version 1.0.0
  * @since 2024-12-19 15:04:54
  */

@Mapper
public interface ExceptionLogAssembler {
    ExceptionLogAssembler INSTANCE = Mappers.getMapper(ExceptionLogAssembler.class);

    ExceptionLogVO convertVO(ExceptionLogEntity exceptionLogEntity);
}