package com.neegix.log.operationLog.application.cqrs.command;

import com.neegix.application.command.ICommand;
import com.neegix.log.operationLog.domain.entity.OperationLogEntity;
import com.neegix.log.operationLog.infrastructure.repository.convert.OperationLogConverter;
import com.neegix.log.operationLog.infrastructure.repository.mapper.OperationLogMapper;
import org.springframework.context.ApplicationContext;

 /**
  * This file is auto-generated by nebula-framework-generator.
  * The auto-generation plugin was developed using IntelliJ IDEA Community Edition.
  * Thanks to JetBrains for their outstanding contributions to the developer community.
  * <p>
  * The code generated by this tool is owned by the user of the tool.
  * The tool itself is copyrighted by <a href="https://www.neegix.com">https://www.neegix.com</a>.
  *
  * @author <a href="https://www.neegix.com">https://www.neegix.com</a>
  * @version 1.0.0
  * @since 2024-11-24 19:51:10
  */

public class UpdateOperationLogCommand implements ICommand<Void> {
    private final OperationLogEntity operationLogEntity;

    public UpdateOperationLogCommand(OperationLogEntity operationLogEntity) {
        this.operationLogEntity = operationLogEntity;
    }

    @Override
    public Void execute(ApplicationContext context) {
        OperationLogMapper operationLogMapper = context.getBean(OperationLogMapper.class);
        operationLogMapper.updateByPrimaryKey(OperationLogConverter.INSTANCE.covertDO(operationLogEntity));
        return null;
    }
}
