package com.neegix.system.role.interfaces.form;

import com.neegix.inferfaces.form.BaseQueryForm;
import lombok.Data;

/**
  * This file is auto-generated by nebula-framework-generator.
  * The auto-generation plugin was developed using IntelliJ IDEA Community Edition.
  * Thanks to JetBrains for their outstanding contributions to the developer community.
  * <p>
  * The code generated by this tool is owned by the user of the tool.
  * The tool itself is copyrighted by <a href="https://www.neegix.com">https://www.neegix.com</a>.
  *
  * @author <a href="https://www.neegix.com">https://www.neegix.com</a>
  * @version 1.0.0
  * @since 2024-11-25 11:32:40
  */

@Data
public class QueryRoleForm extends BaseQueryForm {
    // 角色名称
    private String name;
    // 密码
    private String description;
}


